### ISSUE TITLE
Implement Groceries view

### ISSUE THREAD

**Issue by 22-04-80** [22-04-80/bai-daily-expense-organiser#14]
Widok Groceries
- [x] component Groceries
- [x] component GroceryList
- [x] component AddNewGroceryListButton

Widok formularza dodawania
- [x] component NewGroceryList (zawierający formularz dodawania listy zakupów)

**Comment by qwark97** [comment]
Zostało dokończyć formularz tworzenia nowej listy

**Comment by qwark97** [comment]
Do pełni szczęścia brakuje stylowania
